########################################################
# application.yaml -> default entry point of the application's
# configurations.
########################################################
server:
  port: 8000
spring:

  application:
    name: loan-origination-service

  config:
    import:
      - application-config.yaml
      - application-jwt.yaml